workflows:
  ios-workflow:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Magiccode-flutterIOS
    environment:
      flutter: default
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "PolyTICK.us.app"
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI
        script: |
          keychain initialize
      - name: Fetch / Create signing files from Apple Developer Portal
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build Flutter iOS artifacts
        script: |
          flutter build ios --release --no-codesign
      - name: Package and Sign IPA with Codemagic
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - hafiznoorulhassan987@gmail.com
        notify:
          success: true
          failure: true
